#!/usr/bin/env bash
#
# Copyright (C) <2022>  <Wolkabout Technology s.r.o.>
# This library is free software; you can redistribute it and/or
# modify it under the terms of the GNU Lesser General Public
# License as published by the Free Software Foundation; either
# version 2.1 of the License, or (at your option) any later version.
# This library is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# Lesser General Public License for more details.
# You should have received a copy of the GNU Lesser General Public
# License along with this library; if not, write to the Free Software
#
STYLE=$(git config --get hooks.clangformat.style)

if [ -n "${STYLE}" ] ; then
 STYLEARG="-style=${STYLE}"
else
 STYLEARG="-style=file"
fi

format_file() {
 file="${1}"
 clang-format ${STYLEARG} ${1} -sort-includes -output-replacements-xml | grep "<replacement " >/dev/null
 if [ $? -ne 1 ]
 then
   echo "File ["${1}"] in commit did not match format rules"
   exit 1;
 fi
}

case "${1}" in
 --about )
   echo "Runs clang-format on source files"
   ;;
 * )
   for file in `git diff --cached --name-only --diff-filter=ACMRT | grep -E "^(.*\.(c|cpp|h|hpp)\$)" | grep -v "mpack"` ; do
     format_file "${file}"
   done
   ;;
esac
