
find_package(Threads REQUIRED)

# Define the versions
set(PAHO_MQTT_C_VERSION "1.3.8")
set(PAHO_MQTT_CPP_VERSION "1.2.0")
set(GTEST_VERSION "1.10.0")
set(POCO_VERSION "1.10.1")
set(AWS_SDK_VERSION "1.8.173")
set(NLOHMANN_JSON_VERSION "3.7.3")
set(JSON_SCHEMA_VERSION "2.1.0")
